#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f hawkeye.key; then
  echo "Error: hawkeye.key already exists"
  exit 1
fi

if test -f hawkeye.crt; then
  echo "Error: hawkeye.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out hawkeye.crt -keyout hawkeye.key -subj "/CN=localhost"

chmod 600 hawkeye.crt
chmod 600 hawkeye.key
